### ISSUE TITLE
It won't work...

### ISSUE THREAD

**Issue by Volconon** [geoffreysflaminglasersword/obsidian-living-graph#1]
I don't know what's up, but I've tried multiple times to get this plugin to work, no luck yet.

---
- Does it take some time to start?

- Is it possible it has issues with other plugins?

---
- Thank you for the great plugin, I hope I can get it working; with or without help.

**Comment by ggstrader** [comment]
> I don't know what's up, but I've tried multiple times to get this plugin to work, no luck yet.
> 
> * Does it take some time to start?
> * Is it possible it has issues with other plugins?
> 
> * Thank you for the great plugin, I hope I can get it working; with or without help.

It should start immediately.
It's possible it has issues with other plugins, but doubtful. I don't know of any reason another plugin would conflict as this plugin just finds graph views and changes parameters on them. Also, I have well over 50 plugins installed and it works fine.

Information on your problem would help. What have you done?
Installed/reinstalled?
Enabled?
Used the toggle command?
Tried changing presets?
What version of Obsidian?
Can you share a gif of running the command?
Can you show what, if any, errors show in the dev console? (hit ctrl+shift+i and go to the console tab)

**Comment by geoffreysflaminglasersword** [comment]
> I don't know what's up, but I've tried multiple times to get this plugin to work, no luck yet.
> 
> * Does it take some time to start?
> * Is it possible it has issues with other plugins?
> 
> * Thank you for the great plugin, I hope I can get it working; with or without help.

It should start immediately.
It's possible it has issues with other plugins, but doubtful. I don't know of any reason another plugin would conflict as this plugin just finds graph views and changes parameters on them. Also, I have well over 50 plugins installed and it works fine.

Information on your problem would help. What have you done?
Installed/reinstalled?
Enabled?
Used the toggle command?
Tried changing presets?
What version of Obsidian?
Can you share a gif of running the command?
Can you show what, if any, errors show in the dev console? (hit ctrl+shift+i and go to the console tab)

**Comment by Volconon** [comment]
K, so later that day I found out what the issue was.
The plugin does not initiate without the command being manually used first.
It worked after I found the command to toggle the plugin…😂

Thank you for your time, and help!
Pretty cool plugin if I do say so myself.
